spring:
  application:
    name: enrollment-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/soutrikroy
    username: soutrikroy
    password: Sharanya@24
  server:
    port: 8080
  logging:
    level:
      org.springframework: INFO
      com.example: DEBUG